Repository pickyfarm/pickyFarm, pull requests merged in 2022-03, with the labels that each got.

#123 [#72] 상품 상세 페이지 - 농가 소식 text 정렬
  static_devs/css/products/product_detail.css
Labels: Type: Errors/Bugs, For: Markup/UX

#121 [#117, #118] 소비자 마이페이지 기본 배송지 설정
  static_devs/css/users/mypage/user/mypage_rev_address.css
  static_devs/css/users/mypage/user/mypage_rev_address_mobile.css
  static_devs/images/users/mypage/user/default_address_checked.svg
  static_devs/images/users/mypage/user/default_address_unchecked.svg
  static_devs/js/users/mypage/user/mypage_address.js
  templates/users/mypage_rev_address.html
  users/models.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: For: Models/DB, For: Views, Type: Feature, For: Markup/UX

#127 [#126] 비회원 장바구니 토스트 메세지 변경
  users/views.py
Labels: For: Views, Type: Errors/Bugs

#128 [#119] 고객 배송지 개선사항3 - 마이페이지 관련 배송 정보
  static_devs/css/users/mypage/user/mypage_orders.css
  static_devs/css/users/mypage/user/mypage_orders_mobile.css
  static_devs/images/users/cancel.svg
  static_devs/images/users/complete.svg
  static_devs/images/users/delivering.svg
  static_devs/images/users/preparing.svg
  templates/users/mypage/user/popup_base.html
  templates/users/mypage/user/shipping_info_popup.html
  templates/users/mypage_orders.html
  users/urls.py
  users/views.py
Labels: For: Views, For: Markup/UX

#131 [#130] 리뷰 개선안 Server
  products/views.py
Labels: For: Views, Type: Feature

#133 [#132] 주문 번호 우편정보 추가
  farmers/excels.py
  orders/models.py
  orders/views.py
  templates/orders/payment.html
  templates/orders/payment_non_user.html
Labels: Status: URGENT, For: Models/DB, For: Views, Type: Feature, For: Utils, From: Farmer

#134 [URGENT] 소비자 주문완료 알림톡 admin action
  orders/admin.py
Labels: Status: URGENT, Tag: Purchase, Type: Feature, For: Utils

#135 [#129] 다음 쇼핑하우 EP 다운로드
  products/urls.py
  products/utils.py
  products/views.py
Labels: Type: Feature, For: Utils

#136 [#102] 상품 관련 페이지 리팩토링
  products/tests.py
  products/urls.py
  products/views.py
  static_devs/css/base/grid_layout.css
  static_devs/css/base/mobile_base_style.css
  static_devs/css/products/product_detail_new.css
  static_devs/css/products/product_kind_tag.css
  static_devs/css/products/product_list_new.css
  static_devs/js/products/product_detail.js
  static_devs/js/products/products_list.js
  templates/base/base.html
  templates/products/product_detail.html
  templates/products/product_list_new.html
  templates/products/products_list.html
Labels: For: Views, Type: Refactor, For: Markup/UX, For: Script, Type: Test

#149 [#147] OG 태그 이미지
  static_devs/images/mainlogo_square.png
  static_devs/images/피키팜 로고 jpg.jpg
  templates/base/base_for_index.html
Labels: Type: Errors/Bugs, For: Markup/UX

#150 [#146] 품절 상품 오버레이
  static_devs/css/base/base_style.css
  static_devs/css/products/product_list_new.css
  templates/products/product_detail.html
  templates/products/product_list_new.html
Labels: Type: Feature, For: Markup/UX

#151 [URGENT] 비회원 결제 오류
  templates/orders/payment_non_user.html
Labels: Status: URGENT, Tag: Purchase, Type: Errors/Bugs, For: API, For: Script

#144 [#143] 다음 쇼핑 EP 파일 생성 오류
  products/utils.py
Labels: Type: Errors/Bugs, For: Utils

#156 feat: apply discount - admin action
  products/admin.py
Labels: Type: Feature, For: Utils

#160 fix: apply discount whatever discount price is
  products/admin.py
Labels: Type: Errors/Bugs, For: Utils

#159 Feature/store page discount
  static_devs/css/products/product_detail_new.css
  static_devs/css/products/product_list_new.css
  templates/products/product_detail.html
  templates/products/product_list_new.html
Labels: Type: Feature, For: Markup/UX

#161 feat: disappear unit price desc when does not exist
  templates/products/product_detail.html
Labels: Type: Errors/Bugs, For: Markup/UX

#162 fix: unit price desc
  templates/products/product_detail.html
Labels: Type: Errors/Bugs, For: Markup/UX

#164 [URGENT] 카카오 로그인 문제
  users/views.py
Labels: For: Views, Type: Errors/Bugs, For: API

#165 [URGENT] 상품 배송비 표시
  templates/products/product_detail.html
Labels: Type: Errors/Bugs, For: Markup/UX
