Repository pickyfarm/pickyFarm, pull requests merged in 2022-02, with the labels that each got.

#55 [#51] 에디터스픽 공백 댓글 방지
  static_devs/js/editor_reviews/comment_submit.js
Labels: Errors/Bugs, Script, Slack QA

#56 [#52] 선물하기 주소입력 placeholder
  templates/orders/gift/payment_gift_friends.html
Labels: Purchase, Markup/UX, Slack QA

#65 [#60] 농가 주문목록 엑셀 변환
  farmers/excels.py
Labels: URGENT, Errors/Bugs, Utils, Slack QA

#66 [#61] 농가 송장입력 팝업
  farmers/views.py
  templates/farmers/mypage/order/order_list_section.html
Labels: URGENT, Views, Errors/Bugs, Slack QA

#64 [#62] 배송완료 admin action
  orders/admin.py
Labels: URGENT, Errors/Bugs, Utils, Slack QA

#69 [#68] 송장입력 관련 배송시작 알림 오류 해결
  farmers/views.py
Labels: URGENT, Views, Errors/Bugs

#70 [ ] 비회원 결제 화면 문구 추가
  templates/orders/payment_non_user.html
Labels: URGENT, Markup/UX

#76 [#75] 선물하기 order_group odmn 오류 해결
  orders/models.py
Labels: URGENT, Purchase, Models/DB, Errors/Bugs

#77 [#74] 주문관련 알림톡 재전송 admin action
  orders/admin.py
Labels: URGENT, Feature, Utils

#78 [#74] 배송시작 알림톡 admin action 삭제
  orders/admin.py
Labels: URGENT, Errors/Bugs

#80 [#79] 농가 주문목록 엑셀
  farmers/excels.py
Labels: URGENT, Errors/Bugs, Utils

#82 [#81] consumer admin filter
  users/admin.py
Labels: Feature, Utils

#83 [#81] consumer admin filter
  users/admin.py
Labels: Feature, Utils

#85 [#84] 선물하기 주문 접수 알림톡 전송
  orders/models.py
Labels: URGENT, Purchase, Errors/Bugs, API, Slack QA

#88 [#54] 품절 상품 태그 view 수정
  products/views.py
Labels: Views, Feature

#90 [#54] 품절 상품 태그
  products/views.py
  static_devs/css/products/product_detail.css
  static_devs/css/products/product_detail_mobile.css
  static_devs/css/products/products_list.css
  static_devs/css/products/products_list_mobile.css
  static_devs/js/products/product_detail.js
  templates/products/product_detail.html
  templates/products/products_list.html
Labels: Views, Feature, Markup/UX

#92 [#91] 네이버 DB 업데이트
  products/utils.py
Labels: Utils

#93 [#87] 상품 목록 필터링 기준
  products/views.py
  static_devs/css/base/base_style.css
  templates/partials/header.html
  templates/partials/header_.html
  templates/products/products_list.html
Labels: Views, Feature, Markup/UX

#89 [#86] 상품 상세 설명이미지 0
  products/models.py
  templates/products/detail/product_desc.html
Labels: Models/DB, Feature

#94 FIX: 스토어 리스트 테스트 상품 Exclude
  products/views.py
Labels: URGENT, Errors/Bugs

#97 [#96] 농가 주문목록 엑셀
  farmers/excels.py
Labels: URGENT, Errors/Bugs, Utils, Slack QA

#104 [#103] 선물하기 결제 페이지 오류
  templates/orders/gift/payment_gift_header.html
Labels: Purchase, Errors/Bugs, Slack QA

#106 [#105] 선물하기 Order_Group order_at 필드 오류
  orders/views.py
Labels: URGENT, Purchase, Errors/Bugs, Slack QA

#108 [#107] 구독하기 관련 에러
  static_devs/js/users/mypage/user/mypage_orders.js
  templates/users/mypage_base.html
  templates/users/mypage_orders.html
Labels: Errors/Bugs, Script, Slack QA

#109 [#98] 부트페이 통계
  static_devs/js/base/BootPayStatistics.js
  templates/base/base.html
  templates/orders/payment.html
  templates/products/product_detail.html
Labels: Feature, API, Script

#110 [긴급] 사업자정보 확인
  templates/partials/footer.html
Labels: URGENT, Markup/UX

#113 [#112] 메인페이지 HOT한 무난이 작물
  core/views.py
Labels: URGENT, Views, Errors/Bugs, Slack QA

#114 [긴급] 부트페이 통계
  templates/base/base.html
Labels: Status: URGENT, Type: Errors/Bugs, For: API

#120 [#115, #116] 결제진행 배송지 직접입력
  orders/views.py
  templates/orders/payment.html
Labels: Tag: Purchase, For: Views, Type: Feature, For: API, For: Script
